# https://squidfunk.github.io/mkdocs-material/getting-started/
site_name: Javascript Interface
copyright: Copyright &copy; 2022 <a href="https://github.com/mcxinyu">mcxinyu</a>

repo_name: Javascript Interface
repo_url: https://github.com/mcxinyu/javascript-interface
edit_uri: ""

theme:
  name: material
  language: zh
  palette:
    - media: "(prefers-color-scheme)"
      primary: brown
      toggle:
        icon: material/brightness-auto
        name: 系统主题
    - media: "(prefers-color-scheme: light)"
      primary: brown
      scheme: default
      toggle:
        icon: material/brightness-7
        name: 浅色主题
    - media: "(prefers-color-scheme: dark)"
      primary: black
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: 深色主题
  logo: assets/logo.png
  favicon: assets/favicon.png
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top

plugins:
  - search
  - git-revision-date-localized:
      type: iso_date

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/mcxinyu

nav:
  - 介绍: index.md
  - 文档: api/index.html