name: docs

on:
  push:
    tags:
      - 'docs-*'
  #    paths:
  #      - '.github/workflows/docs.yml'
  #      - 'docs/**'
  #      - 'mkdocs.yml'
  #      - 'core/src/main/java/**'
  #      - 'tbsx5/src/main/java/**'
  workflow_dispatch:
    branches:
      - 'master'
      - 'main'

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: gradle/gradle-build-action@v2
      - name: Build dokka
        run: chmod +x gradlew &&./gradlew dokkaGfmMultiModule --no-daemon --stacktrace
      - name: copy dokka
        run: cp -r build/dokka/gfmMultiModule/ docs/api/
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: |
          pip install mkdocs-material=="9.*"
          pip install jieba
          pip install mkdocs-git-revision-date-localized-plugin
          pip install mike
          git config user.name yuefeng
          git config user.email mcxinyu@foxmail.com
#      - run: mkdocs gh-deploy --force
      - uses: olegtarasov/get-tag@v2.1.2
        id: tag_name
        with:
          tagRegex: "docs-(.*)"
          tagRegexGroup: 1
      - run: |
          mike deploy --push -u ${{ steps.tag_name.outputs.tag }} latest
          mike set-default latest
          mike list
